[package]
name = "mini-anchor-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
bs58 = "0.5.1"
quote = "1.0.43"
sha2 = "0.10.9"
syn = { version = "2.0.114", features = ["full"] }
